---
# Details: https://pre-commit.com/#new-hooks

repos:

# # golangci-lint
# - repo: https://github.com/golangci/golangci-lint
#   rev: v1.55.2
#   hooks:
#    - id: golangci-lint
#      args: [--timeout, 5m] # for CI

 # gofumpt (does not have .pre-commmit-hooks.yaml)
 - repo: local
   hooks:
    - id: gofumpt
      name: "gofumpt"
      additional_dependencies:
       - mvdan.cc/gofumpt@v0.6.0
      entry: "gofumpt"
      language: golang
      args: [-w, .]
      types: [go]
      pass_filenames: false

 # codespell
 - repo: https://github.com/codespell-project/codespell
   rev: v2.2.6
   hooks:
    - id: codespell
      args: [-w]
