# Verify that generated code is up-to-date.
#
# Note that we run these checks regardless whether the input files have
# changed, because generated code can change in response to toolchain updates
# even if no files in the repository are modified.
name: Check generated code
on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  check-mocks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - uses: actions/checkout@v4

      - name: "Check generated mocks"
        run: |
          set -euo pipefail

          make mockery

          if ! git diff --stat --exit-code ; then
            echo ">> ERROR:"
            echo ">>"
            echo ">> Generated mocks require update (either Mockery or source files may have changed)."
            echo ">> Ensure your tools are up-to-date, re-run 'make mockery' and update this PR."
            echo ">>"
            git diff
            exit 1
          fi

  check-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # we need a .git directory to run git diff

      - name: "Check protobuf generated code"
        run: |
          set -euo pipefail

          make proto-gen

          if ! git diff --stat --exit-code ; then
            echo ">> ERROR:"
            echo ">>"
            echo ">> Protobuf generated code requires update (either tools or .proto files may have changed)."
            echo ">> Ensure your tools are up-to-date, re-run 'make proto-gen' and update this PR."
            echo ">>"
            git diff
            exit 1
          fi
