name: Generate Base Benchmark

on:
  workflow_dispatch:
  push:
    paths:
      - "**.go"
      - "!test/**"
    branches:
      - main

jobs:
  gobenchdata-base:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo "GO_VERSION=$(cat .github/workflows/go-version.env | grep GO_VERSION | cut -d '=' -f2)" >> $GITHUB_ENV

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: go install github.com/bobheadxi/gobenchdata@v1.3.1

      - run: go test -bench . -benchmem ./... | gobenchdata --json base.json

      - uses: actions/upload-artifact@v2
        with:
          path: base.json
